set_property SRC_FILE_INFO {cfile:F:/Fly_work/CODE/learn/breathled/breathled.srcs/constrs_1/new/breathctrl.xdc rfile:../../../breathled.srcs/constrs_1/new/breathctrl.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN T4          [get_ports sys_clk_n]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN R4          [get_ports sys_clk_p]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN T6          [get_ports rst_n]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN C17         [get_ports  led[0]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN D17         [get_ports  led[1]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN V20         [get_ports  led[2]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN U20         [get_ports  led[3]]
